### ISSUE TITLE
Searching issues collector 文本搜索集中处理区

### ISSUE THREAD

**Issue by Towdium** [Towdium/JustEnoughCharacters#24]
如果有任何文本搜索不到的问题，类似 #22， #21， #19 ，请在此 issue 下留言
留言前请先确认使用的 JECh 为最新版，并且指明您当前使用的键盘设置（“大千”或“全拼”）
如果您需要的是首字母查询，请在配置文件中打开 z=zh，s=sh，c=ch 模糊音

**Comment by vfyjxf** [comment]
在ae终端内无法搜索物品的英文（类似ME驱动器这种）个人猜测为开启了PinIn的加速模式有关（之前我折腾nech的时候开启加速模式也会有些文本无法匹配的问题，关闭之后就好了）使用键盘设置：全拼
![QQ截图20210827090157](https://user-images.githubusercontent.com/42764413/131055145-59ec819d-bacf-4939-84f2-228ac1a5b98f.png)
![QQ截图20210827090208](https://user-images.githubusercontent.com/42764413/131055150-8b7202d0-e6dc-4483-90cd-8938443a6c64.png)

**Comment by Towdium** [comment]
@vfyjxf 版本号发一下呢？加速模式按理说应该是足够可靠的，索引树倒是可能会有一点风险。下次有搜不出来的也可以发出来看看。

**Comment by vfyjxf** [comment]
> @vfyjxf 版本号发一下呢？加速模式按理说应该是足够可靠的，索引树倒是可能会有一点风险。下次有搜不出来的也可以发出来看看。

1.16.4-4.3.1(mod版本)我nech当初测试使用的是PinIn-1.5.0-all

**Comment by Towdium** [comment]
@vfyjxf 这个是因为 AE 用的是正则匹配，置了忽略大小写的 flag，JECh 原来的实现没有那么细，没有处理这个 flag，导致大小写不能混用。AE 这个场景更怪一些，他在置位忽略大小写之后还将搜索串转了小写，现象就是只能搜小写英文，搜不了大写英文。不管这个特殊处理是出于什么原因，正确处理相关 flag 之后功能就正常了。

**Comment by vfyjxf** [comment]
> @vfyjxf 这个是因为 AE 用的是正则匹配，置了忽略大小写的 flag，JECh 原来的实现没有那么细，没有处理这个 flag，导致大小写不能混用。AE 这个场景更怪一些，他在置位忽略大小写之后还将搜索串转了小写，现象就是只能搜小写英文，搜不了大写英文。不管这个特殊处理是出于什么原因，正确处理相关 flag 之后功能就正常了。

ok，感谢

**Comment by Towdium** [comment]
顺便说，当前版本 JECh 有一个诊断日志的功能 `/jech verbose true` 会把所有执行搜索的原字符串，搜索串和匹配结果都打在 mc 日志里。PinIn 的实时搜索几乎是无状态的，所以目前来看拿到输入参数之后大部分问题都可以稳定复现。

**Comment by vfyjxf** [comment]
![image](https://user-images.githubusercontent.com/42764413/146651103-4f9ed97e-77d9-4584-ae05-b850c87e4b73.png)
![image](https://user-images.githubusercontent.com/42764413/146651125-a40b9a02-d624-4c56-8c70-d693f8700d8b.png)
![image](https://user-images.githubusercontent.com/42764413/146651147-652eb858-0356-4954-a42c-f4dd88c8a879.png)
![image](https://user-images.githubusercontent.com/42764413/146651158-e6b65973-acf3-44df-8d74-f17c0000e6f1.png)
![image](https://user-images.githubusercontent.com/42764413/146651163-d4f7b278-f18f-4844-8e50-764e9bb7c9ed.png)
![image](https://user-images.githubusercontent.com/42764413/146651171-74e35be2-d79c-4834-ae9c-58fa87053416.png)
看起来正则表达式的搜索出了问题了，目前只能搜索英文
jech版本1.16.4-4.3.2 ae版本8.4.4 toms_storage版本1.2.16

**Comment by blackwhita** [comment]
1.12最新版本，无论用任何字符搜索都无反应，通通显示为红字，如图
![`9QFXQ0WC FR8(1{OKHNGPL](https://user-images.githubusercontent.com/98508429/155060851-b3a05a75-3615-4d93-835f-1b0705672f83.png)
![NH~8471)F~03Q3OY0$D SIK](https://user-images.githubusercontent.com/98508429/155060850-e24e5972-f83d-45f9-bbde-f971afb2041d.png)
![50`XY4)$C_N%C%$O%XPR~FU](https://user-images.githubusercontent.com/98508429/155060849-956bc700-c8bb-41bf-941a-44e735426579.png)

**Comment by blackwhita** [comment]
![`9QFXQ0WC FR8(1{OKHNGPL](https://user-images.githubusercontent.com/98508429/155061080-d4035c9c-08b8-4187-a60d-97c1d1a62bcb.png)  
                                            2

**Comment by blackwhita** [comment]
![NH~8471)F~03Q3OY0$D SIK](https://user-images.githubusercontent.com/98508429/155061101-1f828e31-c356-420c-b3d1-1be9d03af589.png)

**Comment by blackwhita** [comment]
如果将JECH去除则正常

**Comment by yang-fu** [comment]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/66714394/195771900-f16fa072-50c2-4ac1-a0bd-beee4b6fe840.png">
AE2 Unofficial Extended Life 没法使用  但是jei没有问题
[jecharacters-profiler.txt](https://github.com/Towdium/JustEnoughCharacters/files/9782842/jecharacters-profiler.txt)

**Comment by vfyjxf** [comment]
> <img alt="image" width="1280" src="https://user-images.githubusercontent.com/66714394/195771900-f16fa072-50c2-4ac1-a0bd-beee4b6fe840.png">
> 
> AE2 Unofficial Extended Life 没法使用 但是jei没有问题 [jecharacters-profiler.txt](https://github.com/Towdium/JustEnoughCharacters/files/9782842/jecharacters-profiler.txt)

这个只是兼容问题，现在已经修复了，更新jech

**Comment by AnonymousGeorgeZhao** [comment]
![AW946~L{R@$6P12QFJZK$6V](https://user-images.githubusercontent.com/92963204/228059898-f819eed9-7dd9-4264-8e27-81d129a7fb05.png)


全拼，使用最新版本jec，1.16.5，jei界面没有显示但是游戏自带的搜索可以使用

**Comment by SihenZhang** [comment]
> ![AW946~L{R@$6P12QFJZK$6V](https://user-images.githubusercontent.com/92963204/228059898-f819eed9-7dd9-4264-8e27-81d129a7fb05.png)
> 
> 全拼，使用最新版本jec，1.16.5，jei界面没有显示但是游戏自带的搜索可以使用

Minecraft Version: 1.16.5
Forge Version: 36.2.39
JEI Version: 7.8.0.1009
JECh Version: 1.16.4-4.3.8
同样的问题，在创造模式物品栏中可以正常搜索，在JEI中不能搜索

**Comment by wyttle** [comment]
Minecraft Version: 1.16.5
Forge Version: 36.2.39
JEI Version: 7.8.0.1009
JECh Version: 1.16.4-4.3.8
ModPack: Enigmatica 6 Expert
同问题 JEI内搜索不生效

**Comment by XingYUmc** [comment]
游戏版本：1.16.5
模组版本：1.16.5-4.5.6
搜索方式：全拼
问题：如图，在配置文件中将sh,zh,ch模糊搜索改为true。不生效，重载后死档，退出存档卡在保存世界中
![%5K81GR$AIVF2KP6U2DO D](https://github.com/Towdium/JustEnoughCharacters/assets/156540470/7a5cff79-cafc-4d68-a6b6-d20497be9ca6)

**Comment by XingYUmc** [comment]
重新检查了一遍，在加入结构指南针，jei,简单存储后。jei，创造模式搜索，配方书均无法正常搜索，结构指南针，简单存储1可以。推测是首字母搜索默认开启了但是对这几个不适配。死档是因为已经开启的东西无法再开一遍

**Comment by Omega9915** [comment]
neoforge v20.4.237 未能加载模组，进入游戏后在mods列表中未能找到jech/Just Enough Char..

**Comment by vfyjxf** [comment]
> neoforge v20.4.237 未能加载模组，进入游戏后在mods列表中未能找到jech/Just Enough Char..

1.20.4不再考虑兼容，只会兼容1.21

**Comment by shanoaice** [comment]
1.20.1 AE2 15.2.x 配上 JECh 4.5.4 的时候在 AE2 终端内搜索不到任何中文内容，AE2 15.1.x 是正常的。感觉好像是新版 AE2 做了一些改动？

**Comment by vfyjxf** [comment]
> 1.20.1 AE2 15.2.x 配上 JECh 4.5.4 的时候在 AE2 终端内搜索不到任何中文内容，AE2 15.1.x 是正常的。感觉好像是新版 AE2 做了一些改动？

现在已经4.5.10了(

**Comment by shanoaice** [comment]
> > 1.20.1 AE2 15.2.x 配上 JECh 4.5.4 的时候在 AE2 终端内搜索不到任何中文内容，AE2 15.1.x 是正常的。感觉好像是新版 AE2 做了一些改动？
> 
> 现在已经4.5.10了(

草了，Modrinth 上没传啊，1.20.1 只有 4.5.4 的，难怪 Prism Launcher 查不到更新

**Comment by vfyjxf** [comment]
> > > 1.20.1 AE2 15.2.x 配上 JECh 4.5.4 的时候在 AE2 终端内搜索不到任何中文内容，AE2 15.1.x 是正常的。感觉好像是新版 AE2 做了一些改动？
> > 
> > 
> > 现在已经4.5.10了(
> 
> 草了，Modrinth 上没传啊，1.20.1 只有 4.5.4 的，难怪 Prism Launcher 查不到更新

Modrinth 没传是因为都是我手动上传的，但是我个人平时就记得传cf，每次传的版本还多就忘了（

**Comment by zhong820290** [comment]
Minecraft Version: 1.21
neoForge Version: 21.0.65
JEI Version: 1.21-neoforge-19.5.0.31
JECh Version: 1.21-4.5.13
ModPack: ATM 10
同问题 加载中崩溃
崩溃报错如下:
Description: Initializing game

net.neoforged.fml.ModLoadingException: Loading errors encountered:
	- ExtendedAE (extendedae) encountered an error while dispatching the net.neoforged.neoforge.client.event.RegisterMenuScreensEvent event
	  java.lang.BootstrapMethodError: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1

	at MC-BOOTSTRAP/fml_loader@4.0.15/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:192) ~[loader-4.0.15.jar%23133!/:4.0] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.15/net.neoforged.fml.ModLoader.lambda$postEvent$13(ModLoader.java:358) ~[loader-4.0.15.jar%23133!/:4.0] {}
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.15/net.neoforged.fml.ModList.forEachModInOrder(ModList.java:164) ~[loader-4.0.15.jar%23133!/:4.0] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.15/net.neoforged.fml.ModLoader.postEvent(ModLoader.java:358) ~[loader-4.0.15.jar%23133!/:4.0] {}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.gui.screens.MenuScreens.init(MenuScreens.java:78) ~[client-1.21-20240613.152323-srg.jar%23330!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/neoforge@21.0.65-beta/net.neoforged.neoforge.client.ClientHooks.initClientHooks(ClientHooks.java:999) ~[neoforge-21.0.65-beta-universal.jar%23331!/:?] {re:mixin,re:classloading,pl:mixin:APP:journeymap.neoforge.mixins.json:client.ClientHooksMixin from mod journeymap,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.<init>(Minecraft.java:601) ~[client-1.21-20240613.152323-srg.jar%23330!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-neoforge.mixins.json:feature.measure_time.MinecraftMixin_Forge from mod modernfix,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:resourcefulconfig.mixins.json:client.MinecraftMixin from mod resourcefulconfig,pl:mixin:APP:omega-config.mixins.json:ClientMixin from mod omegaconfig,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:journeymap.mixins.json:client.MinecraftMixin from mod journeymap,pl:mixin:APP:ichunutil.mixins.json:client.MinecraftMixin from mod ichunutil,pl:mixin:APP:emi.mixins.json:MinecraftClientMixin from mod emi,pl:mixin:APP:kubejs.mixins.json:MinecraftClientMixin from mod kubejs,pl:mixin:APP:mixins/common/nochatreports.mixins.json:client.MixinMinecraft from mod nochatreports,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin from mod embeddium,pl:mixin:APP:embeddium.mixins.json:core.render.MinecraftAccessor from mod embeddium,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin from mod securitycraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.main.Main.main(Main.java:214) ~[client-1.21-20240613.152323-srg.jar%23330!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.15/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.15.jar%23133!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.15/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.15.jar%23133!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.15/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.15.jar%23133!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.15/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.15.jar%23133!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23114!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23114!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23114!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23114!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23114!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23114!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23114!/:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}

看了报错我尝试了把AE拓展模组升级或者降级,还有本模组都升降级,去掉其中一个都可以正常加载到游戏界面.

**Comment by Holy-Fak** [comment]
> > neoforge v20.4.237 未能加载模组，进入游戏后在mods列表中未能找到jech/Just Enough Char..
> 
> 1.20.4不再考虑兼容，只会兼容1.21

想要一个1.20.4的neoforge版本玩 ftb neothch  QAQ
https://www.feed-the-beast.com/modpacks/123-ftb-neotech

**Comment by vfyjxf** [comment]
> 想要一个1.20.4的neoforge版本玩 ftb neothch QAQ https://www.feed-the-beast.com/modpacks/123-ftb-neotech
@Holy-Fak 用这个吧，我实在不想移植下去了https://github.com/TexBlock/JEChUnofficialEdition

**Comment by Holy-Fak** [comment]
> > 想要一个1.20.4的neoforge版本玩 ftb neothch QAQ https://www.feed-the-beast.com/modpacks/123-ftb-neotech
> > @Holy-Fak 用这个吧，我实在不想移植下去了https://github.com/TexBlock/JEChUnofficialEdition

谢谢大佬，大佬辛苦了

**Comment by lenmon1231** [comment]
NeoForge26.2， jecharacters-1.21.10-neoforge-4.6.8.jar，窗口 / 无边框/全屏 模式输入框没办法看到中文候选，只能打出拼音字母，不显示汉字候选弹窗

<img width="1280" height="800" alt="Image" src="https://github.com/user-attachments/assets/718f9bc2-ea6c-4bd1-a4a5-047852b37109" />
<img width="1280" height="800" alt="Image" src="https://github.com/user-attachments/assets/b162a08d-0c36-48d7-8d51-fabad1d88357" />

**Comment by vfyjxf** [comment]
> NeoForge26.2， jecharacters-1.21.10-neoforge-4.6.8.jar，窗口 / 无边框/全屏 模式输入框没办法看到中文候选，只能打出拼音字母，不显示汉字候选弹窗
> <img alt="Image" width="1280" height="800" src="https://private-user-images.githubusercontent.com/119436660/643812170-718f9bc2-ea6c-4bd1-a4a5-047852b37109.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODkxMjAzODIsIm5iZiI6MTc4OTEyMDA4MiwicGF0aCI6Ii8xMTk0MzY2NjAvNjQzODEyMTcwLTcxOGY5YmMyLWVhNmMtNGJkMS1hNGE1LTA0Nzg1MmIzNzEwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDkxMVQwOTQ4MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OTVmZGI5Y2Q4MzNjZmMwZWFjNjQ5MzRjNjczYWFlN2Q4OWU4ZmE2ODQ3MmRiOWZiZjE2YzJkNmQ0YzcwZDRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.bTHU1lPdhMFbtEz1WUvwzsJNn4jdV82IdVXCT7KS15Q"> <img alt="Image" width="1280" height="800" src="https://private-user-images.githubusercontent.com/119436660/643812171-b162a08d-0c36-48d7-8d51-fabad1d88357.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODkxMjAzODIsIm5iZiI6MTc4OTEyMDA4MiwicGF0aCI6Ii8xMTk0MzY2NjAvNjQzODEyMTcxLWIxNjJhMDhkLTBjMzYtNDhkNy04ZDUxLWZhYmFkMWQ4ODM1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDkxMVQwOTQ4MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjU5MTVmYjgwNDZlYTRkYWU1M2VjN2Y3NGUwZDgyOTdmYmU5NGMzNzk4NjlhZmFlNGI1YjU1NTk0MjA0NDlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.GF6ORD9NICC6eQBUPldlcG8fxeeQHig1hCB2_3ZPiEI">

原版就是这样，和jech无关
