### ISSUE TITLE
JustEnoughCharacters-1.12.0-3.7.1版本有个bug

### ISSUE THREAD

**Issue by Ex5261** [Towdium/JustEnoughCharacters#80]
JustEnoughCharacters-1.12.0-3.7.0(?)版本有个bug

好像是与实用拓展Actually Additions有冲突,无法打开游戏

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Actually Additions (actuallyadditions)

Caused by: java.lang.VerifyError: Inconsistent stackmap frames at branch target 149

Exception Details:

  Location:

    de/ellpeck/actuallyadditions/mod/booklet/entry/BookletEntry.fitsFilter(Lde/ellpeck/actuallyadditions/api/booklet/IBookletPage;Ljava/lang/String;)Z @144: ifeq

  Reason:

    Current frame's stack size doesn't match stackmap.

  Current Frame:

    bci: @144

    flags: { }

    locals: { 'de/ellpeck/actuallyadditions/api/booklet/IBookletPage', 'java/lang/String', 'net/minecraft/client/Minecraft', 'java/util/List', 'java/util/Iterator', 'net/minecraft/item/ItemStack', 'java/util/List', 'java/util/Iterator', 'java/lang/String' }

    stack: { 'java/lang/String', integer }

  Stackmap Frame:

    bci: @149

    flags: { }

    locals: { 'de/ellpeck/actuallyadditions/api/booklet/IBookletPage', 'java/lang/String', 'net/minecraft/client/Minecraft', 'java/util/List', 'java/util/Iterator', 'net/minecraft/item/ItemStack', 'java/util/List', 'java/util/Iterator' }

    stack: { }
: 0090 9900 0504 aca7 ffc8 03ac          
  Stackmap Table:
    append_frame(@36,Object[#62],Object[#74],Object[#84])
    full_frame(@88,{Object[#68],Object[#119],Object[#62],Object[#74],Object[#84],Object[#93]},{Object[#93],Object[#121]})
    full_frame(@91,{Object[#68],Object[#119],Object[#62],Object[#74],Object[#84],Object[#93]},{Object[#93],Object[#121],Object[#11]})
    append_frame(@105,Object[#74],Object[#84])
    same_frame(@149)
    chop_frame(@152,3)
    chop_frame(@155,1)
    append_frame(@191,Object[#74],Object[#84])
    same_frame(@247)
    chop_frame(@250,1)

    at de.ellpeck.actuallyadditions.mod.booklet.InitBooklet.preInit(InitBooklet.java:97)
    at de.ellpeck.actuallyadditions.mod.ActuallyAdditions.preInit(ActuallyAdditions.java:93)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:4101)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

这是部分报告

**Comment by vfyjxf** [comment]
先别更新3.7版本吧，我现在在学校没办法修了。

**Comment by Ex5261** [comment]
好像不是3.7.1版本的问题

**Comment by Ex5261** [comment]
不知道从哪里下的3.7.0版本

**Comment by vfyjxf** [comment]
3.7.0我刚才从cf上面下架了，3.7.1应该是修复了 #79 那个问题，应该是一个问题。

**Comment by Ex5261** [comment]
百科没下

**Comment by vfyjxf** [comment]
百科那边我没权限，也不知道能不能下（）
